import 'dart:math';
import 'kind_game_question.dart';

final kidGameRand = Random();

List<T> _pickShuffled<T>(List<T> source, int count) {
  final copy = List<T>.from(source)..shuffle(kidGameRand);
  return copy.take(count).toList();
}

GameQuestion _mcq(
  String prompt,
  String correct,
  List<String> distractors, {
  String? speakWord,
  String? qid,
}) {
  final options = <String>[correct, ...distractors]..shuffle(kidGameRand);
  return GameQuestion(
    prompt: prompt,
    options: options,
    correct: options.indexOf(correct),
    speakWord: speakWord,
    qid: qid ?? prompt,
  );
}

List<GameQuestion> _ensureFifty(List<GameQuestion> qs) {
  if (qs.length >= 50) return qs.take(50).toList();
  // Pad procedurally only if a bank is short (should not happen).
  final out = List<GameQuestion>.from(qs);
  var i = 0;
  while (out.length < 50 && qs.isNotEmpty) {
    final base = qs[i % qs.length];
    out.add(GameQuestion(
      prompt: '${base.prompt} (${out.length + 1})',
      options: base.options,
      correct: base.correct,
      speakWord: base.speakWord,
      qid: '${base.id}_pad_${out.length}',
    ));
    i++;
  }
  return out;
}

// Spelling Bee — 50 words.
const _spellWords = [
  'cat', 'dog', 'sun', 'moon', 'star', 'tree', 'fish', 'bird', 'cake', 'book',
  'ball', 'milk', 'rain', 'frog', 'lion', 'bear', 'duck', 'king', 'ship', 'hand',
  'nose', 'blue', 'green', 'apple', 'house', 'water', 'happy', 'smile', 'tiger',
  'zebra', 'grape', 'table', 'chair', 'plant', 'cloud', 'bread', 'honey', 'mouse',
  'peach', 'lemon', 'river', 'ocean', 'train', 'plane', 'horse', 'sheep', 'queen',
  'clock', 'garden', 'pencil',
];

List<GameQuestion> buildSpellingBee() {
  return _spellWords.map((w) {
    final pos = kidGameRand.nextInt(w.length);
    final missing = w[pos];
    final shown = w.replaceRange(pos, pos + 1, '_').toUpperCase();
    final letters = <String>{missing};
    while (letters.length < 4) {
      letters.add(String.fromCharCode(97 + kidGameRand.nextInt(26)));
    }
    final options = letters.toList()..shuffle(kidGameRand);
    return GameQuestion(
      prompt: 'Spell the word:\n$shown',
      options: options.map((l) => l.toUpperCase()).toList(),
      correct: options.indexOf(missing),
      speakWord: w,
      qid: 'spell_$w',
    );
  }).toList();
}

// Math Challenge — 50 unique problems.
List<GameQuestion> buildMathChallenge() {
  final qs = <GameQuestion>[];
  final seenPrompts = <String>{};
  var guard = 0;
  while (qs.length < 50 && guard < 800) {
    guard++;
    final op = kidGameRand.nextInt(4);
    int a, b, answer;
    String sign;
    if (op == 0) {
      a = kidGameRand.nextInt(40) + 1;
      b = kidGameRand.nextInt(40) + 1;
      answer = a + b;
      sign = '+';
    } else if (op == 1) {
      a = kidGameRand.nextInt(40) + 5;
      b = kidGameRand.nextInt(a) + 1;
      answer = a - b;
      sign = '−';
    } else if (op == 2) {
      a = kidGameRand.nextInt(12) + 1;
      b = kidGameRand.nextInt(12) + 1;
      answer = a * b;
      sign = '×';
    } else {
      b = kidGameRand.nextInt(9) + 2;
      answer = kidGameRand.nextInt(10) + 1;
      a = b * answer;
      sign = '÷';
    }
    final key = '$a$sign$b';
    if (!seenPrompts.add(key)) continue;
    final options = <int>{answer};
    while (options.length < 4) {
      final delta = kidGameRand.nextInt(11) - 5;
      final wrong = answer + delta;
      if (wrong >= 0 && wrong != answer) options.add(wrong);
    }
    final opts = options.map((e) => e.toString()).toList()..shuffle(kidGameRand);
    qs.add(GameQuestion(
      prompt: 'What is\n$a $sign $b = ?',
      options: opts,
      correct: opts.indexOf(answer.toString()),
      qid: 'math_$key',
    ));
  }
  return qs;
}

// Counting Fun — 50.
List<GameQuestion> buildCountingFun() {
  const emojis = [
    '⭐', '🍎', '🐟', '🎈', '🌸', '🚗', '🐝', '🍭', '🐥', '🍓',
    '🐸', '🦋', '🌮', '⚽', '🌻', '🍇', '🧁', '🐼', '🦊', '🐰',
  ];
  final qs = <GameQuestion>[];
  var id = 0;
  for (var n = 1; n <= 10; n++) {
    for (var k = 0; k < 5; k++) {
      final emoji = emojis[id % emojis.length];
      final options = <int>{n};
      while (options.length < 4) {
        final wrong = n + (kidGameRand.nextInt(7) - 3);
        if (wrong >= 1 && wrong <= 12 && wrong != n) options.add(wrong);
      }
      final opts = options.map((e) => e.toString()).toList()..shuffle(kidGameRand);
      qs.add(GameQuestion(
        prompt: 'How many?\n${List.filled(n, emoji).join()}',
        options: opts,
        correct: opts.indexOf(n.toString()),
        qid: 'count_${n}_${k}_$emoji',
      ));
      id++;
      if (qs.length >= 50) return qs;
    }
  }
  return qs;
}

// Word Builder — 50.
List<GameQuestion> buildWordBuilder() {
  final bank = <List<String>>[
    ['A baby dog', 'puppy'],
    ['A place where you learn', 'school'],
    ['Frozen water', 'ice'],
    ['The star we see in the day', 'sun'],
    ['An animal that says "moo"', 'cow'],
    ['A yellow curved fruit', 'banana'],
    ['You wear these on your feet', 'shoes'],
    ['A large gray animal with a trunk', 'elephant'],
    ['The season when it snows', 'winter'],
    ['You use this to write', 'pencil'],
    ['A place with many trees', 'forest'],
    ['The opposite of night', 'day'],
    ['A baby cat', 'kitten'],
    ['You sleep on this at night', 'bed'],
    ['A place where you buy food', 'market'],
    ['The color of grass', 'green'],
    ['A bird that cannot fly, lives in cold places', 'penguin'],
    ['You drink this white liquid from cows', 'milk'],
    ['A vehicle that flies in the sky', 'airplane'],
    ['A round toy you bounce or kick', 'ball'],
    ['The part of your body that pumps blood', 'heart'],
    ['A sweet food made by bees', 'honey'],
    ['A place where sick people get better', 'hospital'],
    ['You use this to cut paper carefully', 'scissors'],
    ['A baby chicken', 'chick'],
    ['The biggest animal in the ocean', 'whale'],
    ['A long yellow fruit monkeys love', 'banana'],
    ['You put this on your head when it is cold', 'hat'],
    ['A book of maps', 'atlas'],
    ['The season after winter when flowers bloom', 'spring'],
    ['A machine that washes clothes', 'washer'],
    ['You use this to call someone', 'phone'],
    ['A place where you watch movies on a big screen', 'cinema'],
    ['The person who flies a plane', 'pilot'],
    ['A place with sand by the sea', 'beach'],
    ['You open this to enter a room', 'door'],
    ['A tool used to see tiny things', 'microscope'],
    ['The opposite of sad', 'happy'],
    ['A fruit that is red and crunchy', 'apple'],
    ['An insect that makes honey', 'bee'],
    ['You write numbers and add them in', 'math'],
    ['A baby frog', 'tadpole'],
    ['The planet we live on', 'earth'],
    ['A tall animal with a long neck', 'giraffe'],
    ['You use this to brush your teeth', 'toothbrush'],
    ['A building where books are kept', 'library'],
    ['The first meal of the day', 'breakfast'],
    ['An animal that hops and has long ears', 'rabbit'],
    ['Water that falls from clouds', 'rain'],
    ['A soft toy animal for children', 'teddy'],
  ];
  final allWords = bank.map((e) => e[1]).toSet().toList();
  return bank.map((pair) {
    final distractors = _pickShuffled(
      allWords.where((w) => w != pair[1]).toList(),
      3,
    );
    return _mcq('Which word means:\n"${pair[0]}"', pair[1], distractors,
        qid: 'word_${pair[1]}_${pair[0].hashCode}');
  }).toList();
}

// ABC Phonics — 50 letters/sounds (including repeats with different correct words).
List<GameQuestion> buildAbcPhonics() {
  final bank = <List<String>>[
    ['A', 'Apple', 'Ball', 'Cat', 'Dog'],
    ['B', 'Banana', 'Sun', 'Fish', 'Tree'],
    ['C', 'Cake', 'Moon', 'Lion', 'Book'],
    ['D', 'Duck', 'Star', 'Apple', 'Hat'],
    ['E', 'Egg', 'Cup', 'Frog', 'Milk'],
    ['F', 'Fish', 'Bird', 'Rain', 'Kite'],
    ['G', 'Goat', 'Nose', 'Cake', 'Doll'],
    ['H', 'House', 'Ball', 'Sun', 'Fox'],
    ['I', 'Ice', 'Dog', 'Cup', 'Fan'],
    ['J', 'Juice', 'Book', 'Pen', 'Hat'],
    ['K', 'Kite', 'Moon', 'Car', 'Bus'],
    ['L', 'Lion', 'Milk', 'Duck', 'Tree'],
    ['M', 'Monkey', 'Star', 'Book', 'Ring'],
    ['N', 'Nest', 'Cat', 'Ball', 'Duck'],
    ['O', 'Orange', 'Fish', 'Hat', 'Pen'],
    ['P', 'Pen', 'Goat', 'Fish', 'Lion'],
    ['Q', 'Queen', 'Dog', 'Cup', 'Tree'],
    ['R', 'Rabbit', 'Moon', 'Cake', 'Doll'],
    ['S', 'Sun', 'Cat', 'Egg', 'Pen'],
    ['T', 'Tiger', 'Ball', 'Fish', 'Cup'],
    ['U', 'Umbrella', 'Dog', 'Hat', 'Bee'],
    ['V', 'Van', 'Sun', 'Cat', 'Bee'],
    ['W', 'Water', 'Moon', 'Pig', 'Cup'],
    ['X', 'Xylophone', 'Dog', 'Hat', 'Bee'],
    ['Y', 'Yarn', 'Cup', 'Fish', 'Dog'],
    ['Z', 'Zebra', 'Ball', 'Moon', 'Cup'],
    ['A', 'Ant', 'Boat', 'Car', 'Door'],
    ['B', 'Book', 'Apple', 'Egg', 'Ice'],
    ['C', 'Car', 'Owl', 'Umbrella', 'Yarn'],
    ['D', 'Door', 'Apple', 'Egg', 'Ice'],
    ['E', 'Elephant', 'Ball', 'Cat', 'Dog'],
    ['F', 'Fox', 'Apple', 'Egg', 'Ice'],
    ['G', 'Grape', 'Ball', 'Cup', 'Dog'],
    ['H', 'Horse', 'Apple', 'Egg', 'Ice'],
    ['L', 'Leaf', 'Ball', 'Cup', 'Dog'],
    ['M', 'Mouse', 'Apple', 'Egg', 'Ice'],
    ['N', 'Net', 'Ball', 'Cup', 'Dog'],
    ['P', 'Pig', 'Apple', 'Egg', 'Ice'],
    ['R', 'Ring', 'Ball', 'Cup', 'Dog'],
    ['S', 'Snake', 'Apple', 'Egg', 'Ice'],
    ['T', 'Tree', 'Ball', 'Cup', 'Dog'],
    ['W', 'Whale', 'Apple', 'Egg', 'Ice'],
    ['B', 'Bread', 'Owl', 'Ice', 'Umbrella'],
    ['C', 'Coin', 'Apple', 'Egg', 'Ice'],
    ['F', 'Flag', 'Owl', 'Egg', 'Ice'],
    ['G', 'Gift', 'Apple', 'Owl', 'Ice'],
    ['H', 'Hill', 'Apple', 'Egg', 'Owl'],
    ['M', 'Map', 'Owl', 'Egg', 'Ice'],
    ['S', 'Socks', 'Apple', 'Egg', 'Ice'],
    ['T', 'Train', 'Owl', 'Egg', 'Ice'],
  ];
  return bank.asMap().entries.map((e) {
    final row = e.value;
    final letter = row[0];
    final correct = row[1];
    return _mcq('Which word starts with the letter "$letter"?', correct,
        [row[2], row[3], row[4]],
        qid: 'abc_${letter}_${e.key}', speakWord: correct);
  }).toList();
}

List<GameQuestion> buildShapesColors() => _ensureFifty([
      _mcq('How many sides does a triangle have?', '3', ['4', '5', '2']),
      _mcq('How many sides does a square have?', '4', ['3', '6', '5']),
      _mcq('What shape is a ball?', 'Circle', ['Square', 'Triangle', 'Star']),
      _mcq('What shape has no corners?', 'Circle',
          ['Square', 'Triangle', 'Rectangle']),
      _mcq('What color is the sky on a sunny day?', 'Blue',
          ['Green', 'Red', 'Brown']),
      _mcq('What color is grass?', 'Green', ['Blue', 'Pink', 'Black']),
      _mcq('What color is a banana?', 'Yellow', ['Purple', 'Blue', 'Green']),
      _mcq('What color do you get mixing red and white?', 'Pink',
          ['Blue', 'Green', 'Black']),
      _mcq('What color is snow?', 'White', ['Black', 'Red', 'Green']),
      _mcq('Which shape has 5 sides?', 'Pentagon',
          ['Square', 'Triangle', 'Circle']),
      _mcq('What color is a ripe tomato?', 'Red', ['Blue', 'Yellow', 'Purple']),
      _mcq('What shape is a slice of pizza?', 'Triangle',
          ['Circle', 'Square', 'Star']),
      _mcq('What color is the sun?', 'Yellow', ['Blue', 'Green', 'Pink']),
      _mcq('How many sides does a rectangle have?', '4', ['3', '5', '6']),
      _mcq('How many corners does a square have?', '4', ['3', '5', '6']),
      _mcq('What shape looks like an egg?', 'Oval',
          ['Square', 'Triangle', 'Star']),
      _mcq('What color do you get mixing blue and yellow?', 'Green',
          ['Orange', 'Purple', 'Brown']),
      _mcq('What color do you get mixing red and yellow?', 'Orange',
          ['Green', 'Purple', 'Blue']),
      _mcq('What color do you get mixing red and blue?', 'Purple',
          ['Green', 'Orange', 'Brown']),
      _mcq('What shape has six sides?', 'Hexagon',
          ['Triangle', 'Square', 'Circle']),
      _mcq('Which shape is used on many flags as a star?', 'Star',
          ['Circle', 'Oval', 'Hexagon']),
      _mcq('What color are most carrots?', 'Orange',
          ['Blue', 'Purple', 'Black']),
      _mcq('What color is chocolate often?', 'Brown',
          ['Blue', 'Pink', 'White']),
      _mcq('How many sides does an octagon have?', '8', ['6', '5', '4']),
      _mcq('A stop sign is closest to which shape?', 'Octagon',
          ['Triangle', 'Circle', 'Star']),
      _mcq('What color is most coal?', 'Black', ['Yellow', 'Pink', 'Green']),
      _mcq('What color is milk?', 'White', ['Blue', 'Green', 'Red']),
      _mcq('A wheel is usually which shape?', 'Circle',
          ['Square', 'Triangle', 'Star']),
      _mcq('A door is closest to which shape?', 'Rectangle',
          ['Circle', 'Triangle', 'Star']),
      _mcq('How many corners does a triangle have?', '3', ['4', '5', '2']),
      _mcq('What color is a ripe lemon?', 'Yellow',
          ['Blue', 'Purple', 'Black']),
      _mcq('What color is a clear daytime cloud often?', 'White',
          ['Green', 'Red', 'Black']),
      _mcq('What shape has equal sides like a diamond on a card?', 'Rhombus',
          ['Circle', 'Oval', 'Sphere']),
      _mcq('What color are many ripe strawberries?', 'Red',
          ['Blue', 'Yellow', 'Brown']),
      _mcq('Which is a warm color?', 'Red', ['Blue', 'Green', 'Cyan']),
      _mcq('Which is a cool color?', 'Blue', ['Orange', 'Red', 'Yellow']),
      _mcq('What color is the Nigerian flag green mixed with?', 'White',
          ['Purple', 'Pink', 'Brown']),
      _mcq('A dice cube has how many faces?', '6', ['4', '5', '8']),
      _mcq('What shape is a full moon closest to?', 'Circle',
          ['Square', 'Triangle', 'Star']),
      _mcq('What color do fire trucks often use?', 'Red',
          ['Purple', 'Green', 'Brown']),
      _mcq('How many sides does a diamond (rhombus) have?', '4',
          ['3', '5', '6']),
      _mcq('What color is most grass after rain?', 'Green',
          ['Blue', 'Pink', 'Black']),
      _mcq('A pyramid side is often which shape?', 'Triangle',
          ['Circle', 'Oval', 'Star']),
      _mcq('Mixing black and white makes?', 'Gray',
          ['Green', 'Orange', 'Purple']),
      _mcq('What color are blueberries?', 'Blue',
          ['Yellow', 'Orange', 'Brown']),
      _mcq('Which shape has one curved side only?', 'Circle',
          ['Square', 'Triangle', 'Pentagon']),
      _mcq('What color is a ruby gem often?', 'Red',
          ['Green', 'Yellow', 'Brown']),
      _mcq('What color is an emerald gem often?', 'Green',
          ['Red', 'Blue', 'Yellow']),
      _mcq('A cube looks like a 3D what?', 'Square',
          ['Circle', 'Triangle', 'Star']),
      _mcq('What color is the ocean often?', 'Blue',
          ['Yellow', 'Pink', 'Orange']),
    ]);

List<GameQuestion> buildOpposites() {
  final pairs = <List<String>>[
    ['big', 'small'],
    ['hot', 'cold'],
    ['up', 'down'],
    ['fast', 'slow'],
    ['happy', 'sad'],
    ['day', 'night'],
    ['open', 'closed'],
    ['tall', 'short'],
    ['old', 'young'],
    ['wet', 'dry'],
    ['clean', 'dirty'],
    ['full', 'empty'],
    ['loud', 'quiet'],
    ['light', 'dark'],
    ['in', 'out'],
    ['left', 'right'],
    ['hard', 'soft'],
    ['heavy', 'light'],
    ['strong', 'weak'],
    ['early', 'late'],
    ['start', 'end'],
    ['front', 'back'],
    ['above', 'below'],
    ['near', 'far'],
    ['rich', 'poor'],
    ['sweet', 'sour'],
    ['wide', 'narrow'],
    ['thick', 'thin'],
    ['alive', 'dead'],
    ['love', 'hate'],
    ['win', 'lose'],
    ['buy', 'sell'],
    ['give', 'take'],
    ['push', 'pull'],
    ['ask', 'answer'],
    ['true', 'false'],
    ['yes', 'no'],
    ['friend', 'enemy'],
    ['brave', 'afraid'],
    ['polite', 'rude'],
    ['asleep', 'awake'],
    ['same', 'different'],
    ['easy', 'hard'],
    ['safe', 'dangerous'],
    ['inside', 'outside'],
    ['before', 'after'],
    ['more', 'less'],
    ['first', 'last'],
    ['male', 'female'],
    ['top', 'bottom'],
  ];
  final allSecond = pairs.map((e) => e[1]).toList();
  return pairs.map((p) {
    final distractors =
        _pickShuffled(allSecond.where((w) => w != p[1]).toList(), 3);
    return _mcq('What is the opposite of "${p[0]}"?', p[1], distractors,
        qid: 'opp_${p[0]}');
  }).toList();
}

List<GameQuestion> buildRhyming() {
  final bank = <List<String>>[
    ['cat', 'hat', 'dog', 'sun'],
    ['ball', 'wall', 'fish', 'tree'],
    ['star', 'car', 'book', 'milk'],
    ['bee', 'tree', 'cup', 'hand'],
    ['cake', 'lake', 'moon', 'duck'],
    ['dog', 'log', 'star', 'ring'],
    ['sun', 'run', 'fish', 'book'],
    ['man', 'pan', 'tree', 'cup'],
    ['bug', 'rug', 'star', 'milk'],
    ['red', 'bed', 'cat', 'sun'],
    ['nose', 'rose', 'ball', 'moon'],
    ['light', 'night', 'duck', 'tree'],
    ['king', 'ring', 'book', 'fish'],
    ['house', 'mouse', 'star', 'pen'],
    ['frog', 'log', 'cake', 'sun'],
    ['ship', 'hip', 'ball', 'moon'],
    ['clock', 'rock', 'fish', 'tree'],
    ['rain', 'train', 'dog', 'cup'],
    ['bike', 'like', 'star', 'milk'],
    ['boat', 'coat', 'fish', 'pen'],
    ['fun', 'run', 'cat', 'book'],
    ['hop', 'top', 'fish', 'moon'],
    ['sing', 'wing', 'ball', 'cup'],
    ['play', 'day', 'fish', 'rock'],
    ['spoon', 'moon', 'cat', 'dog'],
    ['hand', 'sand', 'tree', 'cup'],
    ['ten', 'pen', 'fish', 'moon'],
    ['sit', 'bit', 'ball', 'cup'],
    ['map', 'cap', 'fish', 'tree'],
    ['net', 'pet', 'sun', 'book'],
    ['box', 'fox', 'cake', 'moon'],
    ['jam', 'ham', 'tree', 'cup'],
    ['pin', 'tin', 'fish', 'ball'],
    ['hop', 'mop', 'star', 'cake'],
    ['dig', 'pig', 'moon', 'sun'],
    ['cub', 'tub', 'fish', 'tree'],
    ['fan', 'can', 'book', 'moon'],
    ['lid', 'kid', 'fish', 'star'],
    ['dot', 'pot', 'cake', 'tree'],
    ['leg', 'peg', 'moon', 'fish'],
    ['zip', 'tip', 'ball', 'sun'],
    ['cow', 'now', 'fish', 'cake'],
    ['cry', 'fly', 'book', 'moon'],
    ['door', 'floor', 'fish', 'cup'],
    ['feet', 'meet', 'ball', 'tree'],
    ['goat', 'boat', 'fish', 'pen'],
    ['hill', 'mill', 'moon', 'cake'],
    ['jump', 'bump', 'fish', 'tree'],
    ['kite', 'bite', 'ball', 'cup'],
    ['lamp', 'camp', 'fish', 'moon'],
  ];
  return bank.asMap().entries.map((e) {
    final row = e.value;
    return _mcq('Which word rhymes with "${row[0]}"?', row[1],
        [row[2], row[3], 'top'],
        qid: 'rhyme_${row[0]}_${e.key}');
  }).toList();
}

List<GameQuestion> buildFunQuiz() => _ensureFifty([
      _mcq('How many days are in a week?', '7', ['5', '6', '10']),
      _mcq('What do you get mixing blue and yellow?', 'Green',
          ['Purple', 'Orange', 'Pink']),
      _mcq('How many legs does a spider have?', '8', ['6', '4', '10']),
      _mcq('What shape has three sides?', 'Triangle',
          ['Square', 'Circle', 'Star']),
      _mcq('Which animal is called king of the jungle?', 'Lion',
          ['Zebra', 'Monkey', 'Snake']),
      _mcq('What do bees make?', 'Honey', ['Milk', 'Bread', 'Butter']),
      _mcq('How many colors are in a rainbow?', '7', ['3', '5', '9']),
      _mcq('What comes after the number nine?', 'Ten',
          ['Eight', 'Eleven', 'Zero']),
      _mcq('Which one can you drink?', 'Water', ['Rock', 'Sand', 'Paper']),
      _mcq('What do we use to see?', 'Eyes', ['Ears', 'Nose', 'Hands']),
      _mcq('How many wheels does a bicycle have?', '2', ['3', '4', '1']),
      _mcq('What do we call frozen rain?', 'Snow', ['Steam', 'Fog', 'Wind']),
      _mcq('Which is the biggest?', 'Elephant', ['Ant', 'Mouse', 'Cat']),
      _mcq('What do you wear on a rainy day?', 'Raincoat',
          ['Swimsuit', 'Pajamas', 'Sunglasses']),
      _mcq('How many months have 28 days at least?', 'All of them',
          ['Only February', 'Only January', 'None']),
      _mcq('What do cows give us to drink?', 'Milk', ['Juice', 'Oil', 'Soda']),
      _mcq('Which fruit is typically yellow and curved?', 'Banana',
          ['Apple', 'Grape', 'Orange']),
      _mcq('What do we call a baby dog?', 'Puppy',
          ['Kitten', 'Cub', 'Calf']),
      _mcq('How many fingers on two hands?', '10', ['5', '8', '12']),
      _mcq('What rises in the morning?', 'The sun',
          ['The moon only', 'Stars only', 'Nothing']),
      _mcq('Which is colder?', 'Ice', ['Warm soup', 'Hot tea', 'Fire']),
      _mcq('What do fish live in?', 'Water', ['Trees', 'Sand only', 'Clouds']),
      _mcq('Which number is even?', '4', ['3', '5', '7']),
      _mcq('Which number is odd?', '7', ['2', '4', '8']),
      _mcq('What do we use an umbrella for?', 'Rain',
          ['Sleeping', 'Cooking', 'Singing']),
      _mcq('Which animal has stripes?', 'Zebra', ['Cow', 'Elephant', 'Whale']),
      _mcq('What comes first in the alphabet?', 'A', ['Z', 'M', 'B']),
      _mcq('What comes last in the alphabet?', 'Z', ['A', 'Y', 'B']),
      _mcq('How many sides does a die cube show?', '6', ['4', '5', '8']),
      _mcq('What do birds use to fly?', 'Wings', ['Fins', 'Hooves', 'Claws only']),
      _mcq('Which meal do we eat in the morning?', 'Breakfast',
          ['Dinner', 'Supper only', 'Midnight snack']),
      _mcq('What do you use to write in a notebook?', 'Pencil',
          ['Shoe', 'Spoon', 'Ball']),
      _mcq('Which is a vegetable?', 'Carrot', ['Cake', 'Candy', 'Soda']),
      _mcq('Where do you go to borrow books?', 'Library',
          ['Bakery', 'Garage', 'Beach']),
      _mcq('What do firefighters put out?', 'Fires',
          ['Rain', 'Music', 'Homework']),
      _mcq('How many ears does a person normally have?', '2',
          ['1', '3', '4']),
      _mcq('What do we call water when it boils to gas?', 'Steam',
          ['Ice', 'Snow', 'Rock']),
      _mcq('Which planet do we live on?', 'Earth',
          ['Mars', 'Jupiter', 'Saturn']),
      _mcq('What lights a birthday cake?', 'Candles',
          ['Rocks', 'Shoes', 'Paper alone']),
      _mcq('Which animal hops?', 'Rabbit', ['Fish', 'Snake', 'Worm']),
      _mcq('What is 5 + 5?', '10', ['9', '11', '12']),
      _mcq('What is half of 10?', '5', ['2', '4', '8']),
      _mcq('Which day starts the school week often?', 'Monday',
          ['Sunday always', 'Friday', 'Saturday']),
      _mcq('What do plants grow from?', 'Seeds',
          ['Stones', 'Glass', 'Plastic']),
      _mcq('Which is sweet?', 'Honey', ['Salt', 'Pepper', 'Vinegar']),
      _mcq('What do we call a house on water for boats?', 'Harbor',
          ['Desert', 'Mountain', 'Forest']),
      _mcq('Which tool cuts paper?', 'Scissors',
          ['Spoon', 'Pillow', 'Cup']),
      _mcq('What do you say when you meet someone politely?', 'Hello',
          ['Go away', 'Never', 'Nothing']),
      _mcq('How many halves make a whole?', '2', ['3', '4', '5']),
      _mcq('Which animal lives in a hive?', 'Bee',
          ['Dog', 'Cat', 'Horse']),
    ]);

List<GameQuestion> buildScienceFacts() => _ensureFifty([
      _mcq('What do plants need to grow?', 'Sunlight',
          ['Candy', 'Toys', 'Music']),
      _mcq('What gas do we breathe in to live?', 'Oxygen',
          ['Smoke', 'Helium', 'Dust']),
      _mcq('What planet do we live on?', 'Earth', ['Mars', 'Moon', 'Sun']),
      _mcq('What part of your body pumps blood?', 'Heart',
          ['Brain', 'Lungs', 'Stomach']),
      _mcq('What do we call frozen water?', 'Ice', ['Steam', 'Rain', 'Cloud']),
      _mcq('Which animal can fly?', 'Bird', ['Fish', 'Dog', 'Cat']),
      _mcq('What is the closest star to Earth?', 'The Sun',
          ['The Moon', 'Mars', 'Pluto']),
      _mcq('What do caterpillars turn into?', 'Butterflies',
          ['Fish', 'Frogs', 'Birds']),
      _mcq('Which of these is a liquid?', 'Water', ['Rock', 'Wood', 'Glass']),
      _mcq('What gives us light and heat in the day?', 'The Sun',
          ['The Moon', 'Stars', 'Lamps']),
      _mcq('How many legs does an insect have?', '6', ['4', '8', '2']),
      _mcq('What do we call baby frogs?', 'Tadpoles',
          ['Puppies', 'Chicks', 'Cubs']),
      _mcq('Which one is a source of light?', 'The Sun',
          ['A rock', 'A book', 'A chair']),
      _mcq('What do our lungs help us do?', 'Breathe',
          ['Walk', 'See', 'Hear']),
      _mcq('What pulls objects toward Earth?', 'Gravity',
          ['Magic', 'Wind only', 'Sound']),
      _mcq('What do magnets attract?', 'Iron', ['Wood', 'Plastic', 'Paper']),
      _mcq('Water boils at about how many °C?', '100', ['0', '50', '10']),
      _mcq('Water freezes at about how many °C?', '0', ['100', '50', '25']),
      _mcq('Which sense uses the nose?', 'Smell', ['Sight', 'Hearing', 'Taste']),
      _mcq('Which organ helps you think?', 'Brain',
          ['Liver', 'Skin', 'Foot']),
      _mcq('What covers most of Earth\'s surface?', 'Water',
          ['Desert sand only', 'Cities', 'Ice only']),
      _mcq('What do we call animals that eat plants?', 'Herbivores',
          ['Cars', 'Rocks', 'Clouds']),
      _mcq('What do we call animals that eat meat?', 'Carnivores',
          ['Tables', 'Books', 'Shoes']),
      _mcq('Photosynthesis mainly happens in which plant part?', 'Leaves',
          ['Roots only', 'Flowers only', 'Seeds only']),
      _mcq('What gas do plants take in?', 'Carbon dioxide',
          ['Only helium', 'Only smoke', 'Only steam']),
      _mcq('Shadows are longest when the sun is?', 'Low in the sky',
          ['Directly overhead always', 'Gone forever', 'Inside a room only']),
      _mcq('Sound travels as?', 'Waves', ['Rocks', 'Paper', 'Smoke only']),
      _mcq('Which is a solid?', 'Ice cube', ['Steam', 'Air', 'Fog']),
      _mcq('Which is a gas?', 'Air', ['Stone', 'Wood', 'Ice']),
      _mcq('Bones help your body to?', 'Support and move',
          ['Only taste food', 'Only hear', 'Only smell']),
      _mcq('Your skin helps to?', 'Protect your body',
          ['Pump blood', 'Digest food', 'Make bones']),
      _mcq('Night time happens because Earth?', 'Rotates',
          ['Stops forever', 'Turns into ice', 'Leaves the sun forever']),
      _mcq('Rain comes from?', 'Clouds', ['Rocks', 'Cars', 'Books']),
      _mcq('The Moon has its own light?', 'No, it reflects sunlight',
          ['Yes, always fire', 'Yes, electricity', 'Yes, it is a lamp']),
      _mcq('Electricity can flow through?', 'Metal wires',
          ['Only plastic alone', 'Only wood alone', 'Only rubber alone']),
      _mcq('A thermometer measures?', 'Temperature',
          ['Weight only', 'Speed only', 'Color only']),
      _mcq('Your blood carries?', 'Oxygen and nutrients',
          ['Only stones', 'Only sand', 'Only smoke']),
      _mcq('Fish breathe using?', 'Gills', ['Lungs like us always', 'Wings', 'Fur']),
      _mcq('A tadpole grows into a?', 'Frog', ['Bird', 'Fish forever', 'Cat']),
      _mcq('Seeds need water and what to sprout?', 'Warmth',
          ['Only plastic', 'Only salt', 'Only metal']),
      _mcq('The human body has how many main lungs?', '2',
          ['1', '3', '4']),
      _mcq('What do we call the study of living things?', 'Biology',
          ['Painting', 'Cooking only', 'Singing only']),
      _mcq('Which planet is known as the Red Planet?', 'Mars',
          ['Earth', 'Venus gas only', 'Neptune alone']),
      _mcq('Light travels faster than?', 'Sound',
          ['Nothing ever', 'Only rocks', 'Only water forever']),
      _mcq('Friction can make things?', 'Warm / slower',
          ['Only float forever', 'Only disappear', 'Only sing']),
      _mcq('Recycling helps the?', 'Environment',
          ['Only toys to break', 'Only noise', 'Only darkness']),
      _mcq('A volcano erupts with?', 'Lava', ['Snowballs', 'Cotton', 'Paper']),
      _mcq('Bees help plants by?', 'Pollinating flowers',
          ['Eating all trees', 'Making rocks', 'Stopping rain']),
      _mcq('Your pulse tells you about your?', 'Heartbeat',
          ['Hair color', 'Shoe size', 'Favorite song']),
      _mcq('What do we call hot melted rock underground?', 'Magma',
          ['Cotton', 'Paper', 'Ice cream']),
    ]);

List<GameQuestion> buildGeography() => _ensureFifty([
      _mcq('What is the capital of Nigeria?', 'Abuja',
          ['Lagos', 'Kano', 'Accra']),
      _mcq('What is the largest ocean?', 'Pacific',
          ['Atlantic', 'Indian', 'Arctic']),
      _mcq('On which continent is Egypt?', 'Africa',
          ['Asia', 'Europe', 'America']),
      _mcq('What is the capital of France?', 'Paris',
          ['London', 'Rome', 'Berlin']),
      _mcq('What is the longest river in Africa?', 'Nile',
          ['Niger', 'Congo', 'Amazon']),
      _mcq('How many continents are there?', '7', ['5', '6', '8']),
      _mcq('What is the capital of Ghana?', 'Accra',
          ['Abuja', 'Cairo', 'Nairobi']),
      _mcq('Which country has the Eiffel Tower?', 'France',
          ['Italy', 'Spain', 'Egypt']),
      _mcq('What do we call a very hot, sandy place?', 'Desert',
          ['Ocean', 'Forest', 'Mountain']),
      _mcq('Which is bigger, a country or a city?', 'Country',
          ['City', 'They are equal', 'A street']),
      _mcq('What is the capital of Kenya?', 'Nairobi',
          ['Lagos', 'Cairo', 'Accra']),
      _mcq('What covers most of the Earth?', 'Water',
          ['Sand', 'Grass', 'Ice']),
      _mcq('Which is the hottest place type?', 'Desert',
          ['North Pole', 'Cave', 'River']),
      _mcq('What do we call a mountain that erupts?', 'Volcano',
          ['Hill', 'Valley', 'Island']),
      _mcq('Nigeria is in which continent?', 'Africa',
          ['Asia', 'Europe', 'Australia']),
      _mcq('What is the capital of Egypt?', 'Cairo',
          ['Lagos', 'Accra', 'Nairobi']),
      _mcq('Which ocean is west of Africa?', 'Atlantic',
          ['Pacific only', 'Indian only', 'Arctic only']),
      _mcq('Lagos is in which country?', 'Nigeria',
          ['Ghana', 'Kenya', 'Egypt']),
      _mcq('What separates land areas of water?', 'River / ocean',
          ['Cloud only', 'Book', 'Shoe']),
      _mcq('An island is land surrounded by?', 'Water',
          ['Only sand', 'Only mountains', 'Only trees']),
      _mcq('What is the capital of South Africa (one of)?', 'Pretoria',
          ['Lagos', 'Accra', 'Cairo']),
      _mcq('Mount Everest is in which continent?', 'Asia',
          ['Africa', 'Europe', 'Australia']),
      _mcq('The Sahara is a famous?', 'Desert',
          ['Ocean', 'Forest', 'City']),
      _mcq('Which direction does the sun rise?', 'East',
          ['West', 'North', 'South']),
      _mcq('Which direction does the sun set?', 'West',
          ['East', 'North', 'South']),
      _mcq('A map helps you find?', 'Places',
          ['Only food taste', 'Only music', 'Only colors of paint alone']),
      _mcq('What is a capital city?', 'Seat of government',
          ['Any village', 'Only a farm', 'Only a river']),
      _mcq('Africa is a?', 'Continent', ['Planet', 'Ocean', 'Moon']),
      _mcq('The Amazon is a famous?', 'River',
          ['Desert', 'Mountain only', 'Island only']),
      _mcq('Which country is known for pyramids?', 'Egypt',
          ['Canada', 'Japan', 'Iceland']),
      _mcq('Accra is the capital of?', 'Ghana',
          ['Nigeria', 'Kenya', 'Egypt']),
      _mcq('What do we call land next to the sea?', 'Coast',
          ['Cloud', 'Moon', 'Space']),
      _mcq('Which is denser: city or continent?', 'Continent is larger area',
          ['City is always bigger', 'Same size always', 'Neither exists']),
      _mcq('Lake Chad is near which region?', 'West / Central Africa',
          ['Only Antarctica', 'Only Australia', 'Only Europe always']),
      _mcq('What is weather?', 'Day-to-day conditions',
          ['Only history books', 'Only shoes', 'Only music']),
      _mcq('What is climate?', 'Long-term weather pattern',
          ['Only one cloud', 'Only one rain drop', 'Only a street']),
      _mcq('Which line divides Earth into North and South?', 'Equator',
          ['Moon path', 'Only roads', 'Only rivers forever']),
      _mcq('People who study maps and Earth are often called?', 'Geographers',
          ['Bakers only', 'Pilots only', 'Dentists only']),
      _mcq('What is a valley?', 'Low land between hills',
          ['A tall mountain top only', 'An ocean', 'A cloud']),
      _mcq('What is a peninsula?', 'Land almost surrounded by water',
          ['Only floating ice forever', 'Only a desert square', 'A star']),
      _mcq('Which country borders Nigeria to the west?', 'Benin',
          ['China', 'Brazil', 'Canada']),
      _mcq('Which country borders Nigeria to the east?', 'Cameroon',
          ['Spain', 'Japan', 'Chile']),
      _mcq('What is the capital of Senegal?', 'Dakar',
          ['Lagos', 'Accra', 'Cairo']),
      _mcq('The Indian Ocean is named after?', 'India',
          ['Iceland', 'Ireland only', 'Italy alone']),
      _mcq('Which continent is also a country (large island)?', 'Australia',
          ['Africa always only', 'Europe always only', 'Asia always only']),
      _mcq('What do compasses help you find?', 'Direction',
          ['Only taste', 'Only smell', 'Only sound']),
      _mcq('River Niger flows through?', 'Nigeria (and nearby countries)',
          ['Only Mars', 'Only Antarctica', 'Only the Moon']),
      _mcq('What is a globe?', 'Model of the Earth',
          ['A shoe', 'A spoon', 'A pencil only']),
      _mcq('Which is colder: North Pole or Sahara?', 'North Pole',
          ['Sahara', 'Same always', 'Neither exists']),
      _mcq('Abuja became Nigeria\'s capital after?', 'Lagos',
          ['Accra', 'Cairo', 'Nairobi']),
    ]);

List<GameQuestion> buildAnimals() => _ensureFifty([
      _mcq('Which animal says "moo"?', 'Cow', ['Cat', 'Dog', 'Duck']),
      _mcq('Which animal says "woof"?', 'Dog', ['Cow', 'Sheep', 'Frog']),
      _mcq('Which animal says "quack"?', 'Duck', ['Lion', 'Cat', 'Cow']),
      _mcq('Which animal says "meow"?', 'Cat', ['Dog', 'Goat', 'Bird']),
      _mcq('Which animal has a long trunk?', 'Elephant',
          ['Giraffe', 'Zebra', 'Monkey']),
      _mcq('Which animal has a very long neck?', 'Giraffe',
          ['Lion', 'Pig', 'Rabbit']),
      _mcq('Which animal hops and says "ribbit"?', 'Frog',
          ['Fish', 'Bird', 'Cat']),
      _mcq('Which animal lives in water?', 'Fish', ['Lion', 'Dog', 'Cow']),
      _mcq('Which animal loves bananas?', 'Monkey',
          ['Cow', 'Duck', 'Snake']),
      _mcq('Which animal gives us wool?', 'Sheep',
          ['Horse', 'Fish', 'Cat']),
      _mcq('Which animal can fly?', 'Bird', ['Dog', 'Cow', 'Fish']),
      _mcq('Which animal is very slow and carries its home?', 'Snail',
          ['Rabbit', 'Horse', 'Cheetah']),
      _mcq('Which animal says "oink"?', 'Pig', ['Cat', 'Dog', 'Horse']),
      _mcq('Which animal says "neigh"?', 'Horse', ['Cow', 'Duck', 'Frog']),
      _mcq('Which animal has black and white stripes?', 'Zebra',
          ['Lion', 'Elephant', 'Whale']),
      _mcq('Which animal is the fastest land animal?', 'Cheetah',
          ['Snail', 'Turtle', 'Sloth']),
      _mcq('Which animal has a pouch?', 'Kangaroo',
          ['Dog', 'Cow', 'Chicken']),
      _mcq('Which bird cannot fly and lives in cold places?', 'Penguin',
          ['Eagle', 'Sparrow', 'Parrot']),
      _mcq('Which animal has a hard shell?', 'Turtle',
          ['Rabbit', 'Cat', 'Dog']),
      _mcq('Which animal spins a web?', 'Spider',
          ['Fish', 'Cow', 'Horse']),
      _mcq('Which animal has eight arms (tentacles)?', 'Octopus',
          ['Dog', 'Cat', 'Bird']),
      _mcq('Which animal is known as man\'s best friend?', 'Dog',
          ['Snake', 'Shark', 'Crocodile']),
      _mcq('Which animal lays eggs and quacks?', 'Duck',
          ['Dog', 'Cat', 'Horse']),
      _mcq('Which animal has a mane?', 'Lion', ['Fish', 'Frog', 'Ant']),
      _mcq('Which insect makes honey?', 'Bee', ['Ant', 'Fly', 'Mosquito']),
      _mcq('Which animal changes color to hide?', 'Chameleon',
          ['Elephant', 'Cow', 'Horse']),
      _mcq('Which animal has tusks?', 'Elephant',
          ['Rabbit', 'Chicken', 'Duck']),
      _mcq('Which animal sleeps hanging upside down?', 'Bat',
          ['Dog', 'Cow', 'Horse']),
      _mcq('Which animal is a big cat with spots?', 'Leopard',
          ['Sheep', 'Goat', 'Cow']),
      _mcq('Which farm animal gives us eggs?', 'Chicken',
          ['Dog', 'Cat', 'Horse']),
      _mcq('Which animal lives in the Arctic and is white?', 'Polar bear',
          ['Lion', 'Zebra', 'Tiger']),
      _mcq('Which animal has a bushy striped face and likes trash myths?', 'Raccoon',
          ['Whale', 'Shark', 'Dolphin']),
      _mcq('Which sea animal is smart and jumps?', 'Dolphin',
          ['Ant', 'Worm', 'Snail']),
      _mcq('Which animal says "baa"?', 'Sheep', ['Dog', 'Cat', 'Duck']),
      _mcq('Which animal has antlers?', 'Deer', ['Fish', 'Snake', 'Frog']),
      _mcq('Which animal is famous in Australia and hops?', 'Kangaroo',
          ['Whale', 'Shark', 'Penguin only always']),
      _mcq('Which animal has a hard shell and lives in the sea?', 'Crab',
          ['Cat', 'Dog', 'Cow']),
      _mcq('Which animal is a reptile?', 'Snake',
          ['Dog', 'Cat', 'Rabbit']),
      _mcq('Which animal has feathers?', 'Bird',
          ['Fish', 'Frog', 'Cow']),
      _mcq('Which animal stores food in its cheeks?', 'Hamster',
          ['Whale', 'Shark', 'Eagle']),
      _mcq('Which animal produces milk for people on farms?', 'Cow',
          ['Shark', 'Eagle', 'Snake']),
      _mcq('Which animal is pink and likes mud?', 'Pig',
          ['Eagle', 'Shark', 'Dolphin']),
      _mcq('Which insect has colorful wings?', 'Butterfly',
          ['Worm', 'Snail', 'Ant only']),
      _mcq('Which animal howls at night often?', 'Wolf',
          ['Goldfish', 'Snail', 'Worm']),
      _mcq('Which animal has a shell and is in gardens?', 'Snail',
          ['Eagle', 'Lion', 'Tiger']),
      _mcq('Which animal is black and white and eats bamboo?', 'Panda',
          ['Shark', 'Dolphin', 'Whale']),
      _mcq('Which animal lives in a hive?', 'Bee',
          ['Dog', 'Cat', 'Horse']),
      _mcq('Which animal is used in deserts to carry loads?', 'Camel',
          ['Goldfish', 'Penguin', 'Frog']),
      _mcq('Which animal has a long sticky tongue for ants?', 'Anteater',
          ['Shark', 'Whale', 'Dolphin']),
      _mcq('Which pet animal purrs?', 'Cat', ['Fish', 'Turtle', 'Snake']),
    ]);

List<GameQuestion> buildTimeCalendar() => _ensureFifty([
      _mcq('How many days are in a week?', '7', ['5', '6', '10']),
      _mcq('What day comes after Monday?', 'Tuesday',
          ['Sunday', 'Friday', 'Wednesday']),
      _mcq('What day comes before Sunday?', 'Saturday',
          ['Monday', 'Friday', 'Tuesday']),
      _mcq('How many months are in a year?', '12', ['10', '7', '24']),
      _mcq('Which month is the first of the year?', 'January',
          ['December', 'June', 'March']),
      _mcq('When do we sleep most?', 'Night',
          ['Morning always only', 'Noon only', 'Afternoon only']),
      _mcq('When do we eat breakfast?', 'Morning',
          ['Night', 'Evening', 'Midnight']),
      _mcq('How many hours are in a day?', '24', ['12', '10', '60']),
      _mcq('What comes after Friday?', 'Saturday',
          ['Sunday', 'Monday', 'Thursday']),
      _mcq('How many minutes are in one hour?', '60', ['30', '100', '24']),
      _mcq('Which season is the coldest?', 'Winter',
          ['Summer', 'Spring', 'Autumn']),
      _mcq('When does the sun rise?', 'Morning',
          ['Night', 'Evening', 'Midnight']),
      _mcq('What day is after Tuesday?', 'Wednesday',
          ['Monday', 'Sunday', 'Friday']),
      _mcq('What day is before Friday?', 'Thursday',
          ['Saturday', 'Sunday', 'Monday']),
      _mcq('Which month comes after January?', 'February',
          ['March', 'December', 'April']),
      _mcq('Which month comes before December?', 'November',
          ['January', 'October', 'July']),
      _mcq('How many seconds are in one minute?', '60',
          ['30', '100', '24']),
      _mcq('What do we call the middle of the day?', 'Noon',
          ['Midnight', 'Dawn only', 'Dusk only']),
      _mcq('Christmas is in which month?', 'December',
          ['June', 'March', 'August']),
      _mcq('New Year\'s Day is in?', 'January',
          ['February', 'March', 'April']),
      _mcq('How many weeks are roughly in a year?', '52',
          ['12', '7', '24']),
      _mcq('What comes after Saturday?', 'Sunday',
          ['Monday', 'Friday', 'Thursday']),
      _mcq('What comes before Monday?', 'Sunday',
          ['Tuesday', 'Friday', 'Saturday only never']),
      _mcq('Afternoon comes after?', 'Morning',
          ['Night always', 'Midnight only', 'Nothing']),
      _mcq('Evening comes before?', 'Night',
          ['Morning always', 'Noon always', 'Breakfast']),
      _mcq('A leap year has how many days?', '366',
          ['365', '364', '360']),
      _mcq('February usually has how many days?', '28',
          ['31', '30', '29 always only']),
      _mcq('Which month has 30 days?', 'April',
          ['January', 'March', 'May']),
      _mcq('Which month has Halloween?', 'October',
          ['January', 'June', 'August']),
      _mcq('School often starts on?', 'Monday',
          ['Sunday always', 'Saturday always', 'Never']),
      _mcq('Weekend days are?', 'Saturday and Sunday',
          ['Monday only', 'Tuesday only', 'Wednesday only']),
      _mcq('Dawn is near?', 'Sunrise',
          ['Midnight only', 'Noon only', 'Sunset only']),
      _mcq('Dusk is near?', 'Sunset',
          ['Sunrise only', 'Noon only', 'Midnight only']),
      _mcq('A clock with hands is?', 'Analog clock',
          ['Only a calendar', 'Only a book', 'Only a shoe']),
      _mcq('Digital clocks show time as?', 'Numbers',
          ['Only pictures of cats', 'Only songs', 'Only smells']),
      _mcq('Half an hour is how many minutes?', '30',
          ['15', '45', '60']),
      _mcq('Quarter of an hour is how many minutes?', '15',
          ['30', '45', '60']),
      _mcq('Three months make about a?', 'Season / quarter year',
          ['Day', 'Minute', 'Second']),
      _mcq('Yesterday was before?', 'Today',
          ['Tomorrow only', 'Never', 'Next year only']),
      _mcq('Tomorrow comes after?', 'Today',
          ['Yesterday only forever', 'Never', 'Last year only']),
      _mcq('Spring comes after?', 'Winter',
          ['Summer', 'Autumn only', 'Never']),
      _mcq('Summer is usually?', 'Hot',
          ['Icy always', 'Snowy always', 'Freezing always']),
      _mcq('Autumn is also called?', 'Fall',
          ['Winter only', 'Spring only', 'Summer only']),
      _mcq('A calendar helps you know?', 'Dates',
          ['Only tastes', 'Only sounds', 'Only smells']),
      _mcq('Midday is another word near?', 'Noon',
          ['Midnight', 'Dawn only', 'Dusk only']),
      _mcq('How many days in September?', '30', ['31', '28', '29']),
      _mcq('How many days in July?', '31', ['30', '28', '29']),
      _mcq('What time is 12:00 at night often called?', 'Midnight',
          ['Noon', 'Dawn', 'Afternoon']),
      _mcq('An alarm clock helps you?', 'Wake up',
          ['Only cook', 'Only swim', 'Only fly']),
      _mcq('Which comes first: breakfast or dinner?', 'Breakfast',
          ['Dinner', 'Same time always', 'Neither']),
    ]);

List<GameQuestion> buildGoodManners() => _ensureFifty([
      _mcq('What do you say when someone gives you a gift?', 'Thank you',
          ['Go away', 'No', 'Nothing']),
      _mcq('What do you say when you want something politely?', 'Please',
          ['Now!', 'Give me', 'Hurry']),
      _mcq('What do you say if you bump into someone?', 'Sorry',
          ['Haha', 'Move', 'Nothing']),
      _mcq('What should you do before eating?', 'Wash your hands',
          ['Watch TV', 'Sleep', 'Run']),
      _mcq('How should you talk to your friends?', 'Kindly',
          ['Rudely', 'Loudly shouting', 'Meanly']),
      _mcq('What do you do when someone is talking?', 'Listen',
          ['Shout', 'Ignore them', 'Walk away']),
      _mcq('What should you say in the morning?', 'Good morning',
          ['Goodbye', 'Nothing', 'Go away']),
      _mcq('What do you do with your trash?', 'Put it in the bin',
          ['Throw on floor', 'Hide it', 'Keep it']),
      _mcq('How do you share your toys?', 'Take turns',
          ['Keep them all', 'Hide them', 'Break them']),
      _mcq('What do you say when leaving?', 'Goodbye',
          ['Nothing', 'Give me', 'No']),
      _mcq('What should you do when you cough?', 'Cover your mouth',
          ['Cough on people', 'Do nothing', 'Laugh']),
      _mcq('How do you treat older people?', 'With respect',
          ['Rudely', 'Ignore them', 'Laugh at them']),
      _mcq('What do you say after someone says thank you?', 'You\'re welcome',
          ['No way', 'Go away', 'Never']),
      _mcq('If you need help, you should?', 'Ask politely',
          ['Shout angrily', 'Cry only', 'Steal']),
      _mcq('In line, you should?', 'Wait your turn',
          ['Push others', 'Cut in front', 'Shove']),
      _mcq('At the table, you should?', 'Use kind manners',
          ['Throw food', 'Shout loudly', 'Grab all food']),
      _mcq('If a friend is sad, you should?', 'Comfort them',
          ['Laugh at them', 'Ignore them', 'Tease them']),
      _mcq('Borrowing something means you should?', 'Return it',
          ['Keep it forever', 'Break it', 'Hide it']),
      _mcq('In class you should?', 'Listen to the teacher',
          ['Talk over everyone', 'Throw paper', 'Sleep on floor']),
      _mcq('If you make a mess, you should?', 'Clean it up',
          ['Leave it', 'Blame others', 'Run away']),
      _mcq('Knocking before entering shows?', 'Respect',
          ['Rudeness', 'Anger', 'Fear only']),
      _mcq('Saying "excuse me" helps you?', 'Pass politely',
          ['Be rude', 'Push hard', 'Shout']),
      _mcq('Helping at home is?', 'Good',
          ['Bad', 'Useless', 'Rude']),
      _mcq('Telling the truth is?', 'Honest',
          ['Lying', 'Cheating', 'Stealing']),
      _mcq('Cheating in a game is?', 'Wrong',
          ['Best', 'Funny always', 'Required']),
      _mcq('If someone wins, you can say?', 'Congratulations',
          ['I hate you', 'Cheater forever', 'Nothing mean']),
      _mcq('Sharing snacks means?', 'Being kind',
          ['Being selfish', 'Being rude', 'Being mean']),
      _mcq('On the bus you should?', 'Sit calmly',
          ['Run wild', 'Shout insults', 'Throw trash']),
      _mcq('Greeting your teacher shows?', 'Respect',
          ['Rudeness', 'Anger', 'Hate']),
      _mcq('Using indoor voice means?', 'Speak softly inside',
          ['Scream always', 'Whisper forever only', 'Never talk']),
      _mcq('If you disagree you should?', 'Talk calmly',
          ['Hit someone', 'Yell insults', 'Break things']),
      _mcq('Holding the door for someone is?', 'Kind',
          ['Rude', 'Mean', 'Silly bad']),
      _mcq('Saying please when asking is?', 'Polite',
          ['Rude', 'Angry', 'Lazy']),
      _mcq('Keeping secrets that hurt someone is?', 'Wrong — tell a trusted adult',
          ['Always fun', 'Best forever', 'Required']),
      _mcq('Hands to yourself means?', 'Don\'t hit or grab',
          ['Push everyone', 'Pull hair', 'Kick']),
      _mcq('When visiting, you should?', 'Be polite guests',
          ['Break things', 'Scream', 'Make a mess and leave']),
      _mcq('Waiting quietly shows?', 'Patience',
          ['Rudeness', 'Anger', 'Meanness']),
      _mcq('Thanking the cook for food is?', 'Good manners',
          ['Bad manners', 'Useless', 'Rude']),
      _mcq('Calling people mean names is?', 'Unkind',
          ['Friendly', 'Kind', 'Polite']),
      _mcq('If you lose, you should?', 'Be a good sport',
          ['Cry forever angrily', 'Hit winners', 'Quit manners']),
      _mcq('Helping a new classmate is?', 'Kind',
          ['Mean', 'Rude', 'Selfish']),
      _mcq('Putting toys away is?', 'Responsible',
          ['Lazy good', 'Rude', 'Mean']),
      _mcq('Listening when parents speak is?', 'Respectful',
          ['Rude', 'Loud rude', 'Ignoring']),
      _mcq('Using tissues for a runny nose is?', 'Clean manners',
          ['Dirty habits', 'Rude', 'Mean']),
      _mcq('Saying "may I" instead of grabbing is?', 'Polite',
          ['Rude', 'Mean', 'Angry']),
      _mcq('Keeping promises to friends is?', 'Trustworthy',
          ['Lying', 'Cheating', 'Rude']),
      _mcq('Quiet feet in the library means?', 'Walk softly',
          ['Run and yell', 'Slam books', 'Throw chairs']),
      _mcq('Apologizing when wrong shows?', 'Responsibility',
          ['Pride only', 'Rudeness', 'Meanness']),
      _mcq('Smiling at friends can show?', 'Friendliness',
          ['Anger', 'Hate', 'Fear only']),
      _mcq('Waiting to speak until called on is?', 'Good classroom manners',
          ['Rude', 'Loud', 'Mean']),
    ]);

List<GameQuestion> buildMyBody() => _ensureFifty([
      _mcq('What do you use to see?', 'Eyes', ['Ears', 'Nose', 'Feet']),
      _mcq('What do you use to hear?', 'Ears', ['Eyes', 'Hands', 'Nose']),
      _mcq('What do you use to smell?', 'Nose', ['Eyes', 'Ears', 'Feet']),
      _mcq('What do you use to walk?', 'Legs', ['Hands', 'Ears', 'Eyes']),
      _mcq('How many fingers are on one hand?', '5', ['4', '10', '6']),
      _mcq('What do you use to taste?', 'Tongue', ['Nose', 'Eyes', 'Ears']),
      _mcq('What should you brush every day?', 'Teeth',
          ['Windows', 'Shoes', 'Walls']),
      _mcq('What food is healthy?', 'Fruits',
          ['Candy', 'Chips', 'Soda']),
      _mcq('What should you drink to stay healthy?', 'Water',
          ['Soda', 'Juice only', 'Nothing']),
      _mcq('What helps you grow strong?', 'Healthy food',
          ['Only sweets', 'No sleep', 'Junk food']),
      _mcq('How many eyes do you have?', '2', ['1', '3', '4']),
      _mcq('What do you do when you are tired?', 'Rest and sleep',
          ['Run more', 'Skip sleep', 'Stay up all night']),
      _mcq('What pumps blood around your body?', 'Heart',
          ['Hair', 'Nails', 'Ears']),
      _mcq('What helps you think and learn?', 'Brain',
          ['Toes', 'Elbows', 'Knees only']),
      _mcq('What do lungs help you do?', 'Breathe',
          ['Taste candy', 'Grow hair', 'Blink only']),
      _mcq('How many toes on two feet?', '10', ['5', '8', '12']),
      _mcq('Skin helps to?', 'Protect your body',
          ['Pump blood', 'Digest food', 'Make bones']),
      _mcq('Bones help you to?', 'Stand and move',
          ['Only smell', 'Only hear', 'Only taste']),
      _mcq('Muscles help you to?', 'Move',
          ['Only sleep forever', 'Only smell', 'Only hear']),
      _mcq('You should wash hands before?', 'Eating',
          ['Only sleeping forever', 'Never', 'Only watching TV']),
      _mcq('Exercise helps your body stay?', 'Healthy',
          ['Weaker forever', 'Sick always', 'Tired forever']),
      _mcq('Sleep helps your body?', 'Rest and grow',
          ['Only get weaker', 'Only get sick', 'Only forget']),
      _mcq('Elbows are joints in your?', 'Arms',
          ['Ears', 'Nose', 'Hair']),
      _mcq('Knees are joints in your?', 'Legs',
          ['Ears', 'Nose', 'Hair']),
      _mcq('Your spine is also called?', 'Backbone',
          ['Eyeball', 'Fingernail', 'Eyelash']),
      _mcq('Blood is pumped by the?', 'Heart',
          ['Hair', 'Teeth', 'Nails']),
      _mcq('You chew food with your?', 'Teeth',
          ['Ears', 'Elbows', 'Knees']),
      _mcq('You swallow food down your?', 'Throat',
          ['Ears', 'Toes', 'Hair']),
      _mcq('Stomach helps to?', 'Digest food',
          ['Hear music', 'See colors', 'Smell flowers only']),
      _mcq('Eyes need rest from too much?', 'Screen time',
          ['Water', 'Sleep', 'Fresh air']),
      _mcq('Ears help with?', 'Hearing',
          ['Smelling only', 'Tasting only', 'Walking only']),
      _mcq('Nose helps with?', 'Smell and breathing',
          ['Hearing only', 'Tasting sweets only', 'Writing']),
      _mcq('Hands help you?', 'Hold and write',
          ['Only hear', 'Only smell', 'Only taste air']),
      _mcq('Feet help you?', 'Stand and walk',
          ['Only hear', 'Only smell', 'Only see']),
      _mcq('Hair grows on your?', 'Head (and body)',
          ['Only inside lungs', 'Only inside heart', 'Only bones']),
      _mcq('Nails protect tips of?', 'Fingers and toes',
          ['Ears', 'Eyes', 'Nose insides']),
      _mcq('A doctor check-up helps you stay?', 'Healthy',
          ['Unhealthy', 'Sleepy forever', 'Angry']),
      _mcq('Vitamins often come from?', 'Fruits and vegetables',
          ['Only candy', 'Only soda', 'Only chips']),
      _mcq('Too much sugar is?', 'Unhealthy',
          ['Always best', 'Required every second', 'Never an issue']),
      _mcq('Brushing teeth prevents?', 'Cavities / tooth decay',
          ['Growing taller forever', 'Hearing better forever', 'Flying']),
      _mcq('Your pulse is linked to your?', 'Heartbeat',
          ['Hair length', 'Shoe size', 'Favorite color']),
      _mcq('Wearing a helmet protects your?', 'Head',
          ['Only toes', 'Only fingernails', 'Only hair color']),
      _mcq('Sunscreen protects your?', 'Skin',
          ['Only bones inside', 'Only blood', 'Only brain thinking only']),
      _mcq('Crying tears come from?', 'Eyes',
          ['Ears', 'Knees', 'Elbows']),
      _mcq('Sweat helps cool your?', 'Body',
          ['Only books', 'Only shoes', 'Only chairs']),
      _mcq('You have one?', 'Nose', ['Two noses', 'Three noses', 'No nose']),
      _mcq('Balanced meals include?', 'Different healthy foods',
          ['Only candy', 'Only soda', 'Only chips']),
      _mcq('Germs can spread by?', 'Dirty hands',
          ['Only singing', 'Only smiling', 'Only sleeping well']),
      _mcq('Covering a sneeze protects?', 'Others from germs',
          ['Nobody ever', 'Only toys', 'Only chairs']),
      _mcq('Your brain is inside your?', 'Head / skull',
          ['Foot', 'Hand only', 'Knee only']),
    ]);
